//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForecastApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int ForecastID { get; set; }
        public string Location { get; set; }
        public int Degree { get; set; }
        public string Image { get; set; }
        public int Rain { get; set; }
        public int Wind { get; set; }
        public string Direction { get; set; }
        public System.DateTime Date { get; set; }
        public string Day { get; set; }
        public string DayTuesday { get; set; }
        public int TuesdayDegree { get; set; }
        public int TuesdayRain { get; set; }
        public string DayWednesday { get; set; }
        public int WednesdayDegree { get; set; }
        public int WednesdayRain { get; set; }
        public string DayThursday { get; set; }
        public int ThursdayDegree { get; set; }
        public int ThursdayRain { get; set; }
        public string DayFriday { get; set; }
        public int FridayDegree { get; set; }
        public int FridayRain { get; set; }
        public string DaySaturday { get; set; }
        public int SaturdayDegree { get; set; }
        public int SaturdayRain { get; set; }
        public string DaySunday { get; set; }
        public int SundayDegree { get; set; }
        public int SundayRain { get; set; }
    }
}
